=== winwin17/window11/webpractice/exteddtd1.dtd
<!ELEMENT weather(date,city,state,country,temp)>
<!ELEMENT date(#PCDATA)>
<!ELEMENT city(#PCDATA)>
<!ELEMENT state(#PCDATA)>
<!ELEMENT country(#PCDATA)>
<!ELEMENT temp(high,low,mrng,aft,eve)>
<!ELEMENT high(#PCDATA)>
<!ATTLIST high scale CDATA #REQUIRED>
<!ELEMENT low(#PCDATA)>
<!ATTLIST low scale CDATA #REQUIRED>
<!ELEMENT mrng(#PCDATA)>
<!ELEMENT aft(#PCDATA)>
<!ELEMENT eve(#PCDATA)>

=== winwin17/window11/webpractice/prc1.xml
<?xml version="1.0"?>
<!DOCTYPE weather SYSTEM "exteddtd1.dtd">
<weather>
<date>1/2/2024</date>
<city>NY</city>
<state> TN</state>
<temp>
<high sclae="F">103</high>
<low sclae="F">10</low>
<mrng>party</mrng>
<aft>sunny</aft>
<eve>cloudy</eve>
</temp>
</weather>
